#!/bin/bash
npx typedoc

rm -rf ../Iridium-Docs/*

echo """
\`\`\`
██╗██████╗ ██╗██████╗ ██╗██╗   ██╗███╗   ███╗
██║██╔══██╗██║██╔══██╗██║██║   ██║████╗ ████║
██║██████╔╝██║██║  ██║██║██║   ██║██╔████╔██║
██║██╔══██╗██║██║  ██║██║██║   ██║██║╚██╔╝██║
██║██║  ██║██║██████╔╝██║╚██████╔╝██║ ╚═╝ ██║
╚═╝╚═╝  ╚═╝╚═╝╚═════╝ ╚═╝ ╚═════╝ ╚═╝     ╚═╝
\`\`\`
Link: https://compl-research.github.io/Iridium-Docs/

This is an autogenerated page updated everytime we do changes to the Iridium IR documentation.
Expect it to be changed rapidly in the beginning and slowly reach cruize control. :)
""" > ../Iridium-Docs/README.md

cp -r docs/* ../Iridium-Docs

cd ../Iridium-Docs/

git add -A

git commit -am "Publish Documentation: `date`"

git push