#!/usr/bin/env bash
set -euo pipefail

rm -rf tmp
mkdir tmp
# Test
TESTS=(
  # "test/language/expressions/addition"
  # "test/language/expressions/array"
  "test/language/expressions/arrow-function"
  # "test/language/expressions/assignment"
  # "test/language/expressions/assignmenttargettype"
  # "test/language/expressions/async-arrow-function"
  # "test/language/expressions/async-function"
  # "test/language/expressions/async-generator"
  # "test/language/expressions/await"
  # "test/language/expressions/bitwise-and"
  # "test/language/expressions/bitwise-not"
  # "test/language/expressions/bitwise-or"
  # "test/language/expressions/bitwise-xor"
  # "test/language/expressions/call"
  # "test/language/expressions/class"
  # "test/language/expressions/coalesce"
  # "test/language/expressions/comma"
  # "test/language/expressions/compound-assignment"
  # "test/language/expressions/concatenation"
  # "test/language/expressions/conditional"
  # "test/language/expressions/delete"
  # "test/language/expressions/division"
  # "test/language/expressions/does-not-equals"
  # "test/language/expressions/dynamic-import"
  # "test/language/expressions/equals"
  # "test/language/expressions/exponentiation"
  # "test/language/expressions/function"
  # "test/language/expressions/generators"
  # "test/language/expressions/greater-than-or-equal"
  # "test/language/expressions/greater-than"
  # "test/language/expressions/grouping"
  # "test/language/expressions/import.meta"
  # "test/language/expressions/in"
  # "test/language/expressions/instanceof"
  # "test/language/expressions/left-shift"
  # "test/language/expressions/less-than-or-equal"
  # "test/language/expressions/less-than"
  # "test/language/expressions/logical-and"
  # "test/language/expressions/logical-assignment"
  # "test/language/expressions/logical-not"
  # "test/language/expressions/logical-or"
  # "test/language/expressions/member-expression"
  # "test/language/expressions/modulus"
  # "test/language/expressions/multiplication"
  # "test/language/expressions/new.target"
  # "test/language/expressions/new"
  # "test/language/expressions/object"
  # "test/language/expressions/optional-chaining"
  # "test/language/expressions/postfix-decrement"
  # "test/language/expressions/postfix-increment"
  # "test/language/expressions/prefix-decrement"
  # "test/language/expressions/prefix-increment"
  # "test/language/expressions/property-accessors"
  # "test/language/expressions/relational"
  # "test/language/expressions/right-shift"
  # "test/language/expressions/strict-does-not-equals"
  # "test/language/expressions/strict-equals"
  # "test/language/expressions/subtraction"
  # "test/language/expressions/super"
  # "test/language/expressions/tagged-template"
  # "test/language/expressions/template-literal"
  # "test/language/expressions/this"
  # "test/language/expressions/typeof"
  # "test/language/expressions/unary-minus"
  # "test/language/expressions/unary-plus"
  # "test/language/expressions/unsigned-right-shift"
  # "test/language/expressions/void"
  # "test/language/expressions/yield"


  # "test/language/arguments-object"
  # "test/language/asi"
  # "test/language/block-scope"
  # "test/language/comments"
  # "test/language/computed-property-names"
  # "test/language/destructuring"
  # "test/language/directive-prologue"
  # "test/language/eval-code"
  # "test/language/export"
  # "test/language/expressions"
  # "test/language/function-code"
  # "test/language/future-reserved-words"
  # "test/language/global-code"
  # "test/language/identifier-resolution"
  # "test/language/identifiers"
  # "test/language/import"
  # "test/language/keywords"
  # "test/language/line-terminators"
  # "test/language/literals"
  # "test/language/module-code"
  # "test/language/punctuators"
  # "test/language/reserved-words"
  # "test/language/rest-parameters"
  # "test/language/source-text"
  # "test/language/start"
  # "test/language/statementList"
  # "test/language/statements"
  # "test/language/types"
  # "test/language/white-space"
)

for test in "${TESTS[@]}"; do
  outFile="out_${test//\//_}"
  echo "Running $test -> $outFile"
  node run.cjs "$test/" > "$outFile"
done
