import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

import AUTHORS from "../Authors";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, "package.json"), "utf8"));

// JSON strings are valid YAML double-quoted scalars
const q = (s: string) => JSON.stringify(s);

const lines = [
  "# This file is generated by scripts/genCitation.ts from Authors.ts. Do not edit by hand.",
  "cff-version: 1.2.0",
  'message: "If you use Iridium in your research, please cite it as below."',
  "type: software",
  "title: Iridium",
  `abstract: ${q("A static analysis framework for JavaScript programs.")}`,
  `version: ${q(pkg.version)}`,
  `license: ${pkg.license}`,
  "url: https://compl-research.github.io/Iridium/",
  "repository-code: https://github.com/compl-research/Iridium",
  "keywords:",
  "  - static analysis",
  "  - JavaScript",
  "  - intermediate representation",
  "  - compiler",
  "authors:",
];

for (const a of AUTHORS) {
  lines.push(`  - given-names: ${q(a.givenNames)}`);
  if (a.familyNames) lines.push(`    family-names: ${q(a.familyNames)}`);
  lines.push(`    affiliation: ${q(a.affiliation)}`);
  if (a.email) lines.push(`    email: ${q(a.email)}`);
  if (a.orcid) lines.push(`    orcid: ${q(a.orcid)}`);
}

fs.writeFileSync(path.join(ROOT, "CITATION.cff"), lines.join("\n") + "\n");
console.log(`Wrote CITATION.cff (${AUTHORS.length} authors)`);

// BibTeX entry, included by the website's About page
const bibAuthors = AUTHORS.map((a) =>
  a.familyNames ? `${a.familyNames}, ${a.givenNames}` : a.givenNames,
).join(" and ");

const bib = [
  "@software{iridium,",
  `  author  = {${bibAuthors}},`,
  "  title   = {Iridium},",
  `  version = {${pkg.version}},`,
  `  license = {${pkg.license}},`,
  "  url     = {https://github.com/compl-research/Iridium},",
  "}",
];

const bibPath = path.join(ROOT, "website", "assets", "iridium.bib");
fs.mkdirSync(path.dirname(bibPath), { recursive: true });
fs.writeFileSync(bibPath, bib.join("\n") + "\n");
console.log("Wrote website/assets/iridium.bib");
